import { ResizableWorkbench } from '../components/layout/ResizableWorkbench';
import { useState } from 'react';
import { ArrowRight, ChevronRight, FileText, Folder, FolderOpen, ListFilter, Search, SlidersHorizontal } from 'lucide-react';
import { useAppStore } from '../stores/appStore';
import type { Run } from '../api/client';

export function HomePage() {
  const s = useAppStore();
  const [mode, setMode] = useState<'all'|'capacity'|'diversion'>('all');
  const [query, setQuery] = useState('');
  const [picked, setPicked] = useState<number | null>(s.selectedRunId);
  const all = [...s.runs].sort((a,b) => b.id-a.id);
  const jobs = all.filter(r => (mode === 'all' || r.model_type === mode) && `${r.id} ${r.name} ${r.traction}`.toLowerCase().includes(query.toLowerCase()));
  const selected = jobs.find(r => r.id === picked) ?? jobs[0];
  const open = (run: Run) => { s.selectRun(run.id); s.setPage(run.status === 'complete' ? 'results' : 'runs'); };
  const paths = (r: Run) => r.status !== 'complete' ? '—' : r.model_type === 'diversion' ? r.div_placed ?? '—' : (r.up_inserted ?? 0)+(r.down_inserted ?? 0);
  return <ResizableWorkbench>
    <aside className="project-explorer"><header><FolderOpen size={14}/> PROJECT EXPLORER</header><div className="explorer-root"><ChevronRight size={13}/><FolderOpen size={15}/> Railway studies</div><div className="register-tabs explorer-tree">{(['all','capacity','diversion'] as const).map(t => <button key={t} aria-pressed={mode === t} className={mode === t ? 'selected' : ''} onClick={() => setMode(t)}><Folder size={14}/><span>{t === 'all' ? 'All studies' : t === 'capacity' ? 'Capacity' : 'Diversion'}</span><small>{t === 'all' ? all.length : all.filter(r=>r.model_type === t).length}</small></button>)}</div><h3>PROJECT RESOURCES</h3><button className="resource-entry" onClick={()=>s.setPage('upload')}><FileText size={14}/> TD datasets <small>{s.uploads.length}</small></button><button className="resource-entry" onClick={()=>s.setPage('corridor')}><Folder size={14}/> Corridors <small>{s.corridors.length}</small></button><button className="resource-entry" onClick={()=>s.setPage('tpr')}><FileText size={14}/> Planning rules</button></aside>
    <section className="study-editor study-register"><div className="document-tabs"><span><FileText size={14}/> Study workspace</span></div><div className="editor-toolbar"><span><ListFilter size={14}/>{mode === 'all' ? 'All studies' : mode === 'capacity' ? 'Capacity studies' : 'Diversion studies'}</span><label><Search size={14}/><input aria-label="Search studies" placeholder="Filter studies…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="study-table-scroll"><table><thead><tr><th className="row-index">#</th><th>Study name</th><th>Model</th><th>Date</th><th>State</th><th>Paths</th><th/></tr></thead><tbody>{jobs.map((r,i)=><tr key={r.id} className={selected?.id === r.id ? 'selected-row' : ''} onClick={()=>setPicked(r.id)} onDoubleClick={()=>open(r)}><td className="row-index">{String(i+1).padStart(2,'0')}</td><td><button className="study-select" aria-pressed={selected?.id === r.id} onClick={()=>setPicked(r.id)}><FileText size={14}/><span>{r.name}</span></button></td><td>{r.model_type}</td><td>{r.date_tag ?? 'All dates'}</td><td><span className={`plain-state ${r.status}`}>{r.status}</span></td><td className="numeric">{paths(r)}</td><td><button className="open-study" aria-label={`Open study ${r.id}`} onClick={e=>{e.stopPropagation();open(r);}}><ArrowRight size={13}/></button></td></tr>)}</tbody></table>{!jobs.length && <div className="editor-empty"><FolderOpen size={28}/><strong>{all.length ? 'No matching studies' : 'Your study register is empty'}</strong><p>{all.length ? 'Change the filter to show more studies.' : 'Use New capacity study or New diversion to begin.'}</p></div>}</div><div className="editor-status"><span>{jobs.length} records</span><span>{selected ? `Selected: run ${selected.id}` : 'No selection'}</span><span>Double-click a study to open</span></div></section>
    <aside className="properties-inspector"><header><SlidersHorizontal size={14}/> STUDY PROPERTIES</header>{selected ? <><div className="property-identity"><span>RUN {String(selected.id).padStart(4,'0')}</span><h2>{selected.name}</h2><button onClick={()=>open(selected)}>{selected.status === 'complete' ? 'Open analysis' : 'Open run monitor'}<ArrowRight size={14}/></button></div><h3>DEFINITION</h3><dl>{[['Model',selected.model_type],['Service date',selected.date_tag ?? 'All dates'],['Traction',selected.traction || '—'],['State',selected.status],['Created',new Date(selected.created_at).toLocaleDateString('en-GB')]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>OPERATING PARAMETERS</h3><dl>{[['Headway',`${selected.headway_min} min`],['Maximum dwell',`${selected.dwell_max} min`],['Block length',`${selected.block_hours} h`],['Solve limit',`${selected.time_limit_per_block} s`]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>RESULT SUMMARY</h3><dl><div><dt>Paths placed</dt><dd>{paths(selected)}</dd></div><div><dt>Solve time</dt><dd>{selected.wall_solve_time_s == null ? '—' : `${Math.round(selected.wall_solve_time_s)} s`}</dd></div></dl></> : <p className="inspector-empty">Select a study to inspect its parameters and results.</p>}</aside>
  </ResizableWorkbench>;
}
